version: 2.1

executors:
  node-10-16:
    docker:
      - image: circleci/node:10.16

jobs:
  build:
    executor: node-10-16
    working_directory: ~/client
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test

workflows:
  test:
    jobs:
      - build
